In [1]:
import numpy as np

In [2]:
# Array creation
a = np.array([1, 2, 3, 4, 5])
zeros = np.zeros((3, 4))
ones = np.ones((2, 2))
random_arr = np.random.rand(3, 3)
print(a, "\n", zeros, "\n", ones, "\n", random_arr)

[1 2 3 4 5] 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 [[1. 1.]
 [1. 1.]] 
 [[0.24990532 0.58297236 0.45609566]
 [0.2676142  0.77805993 0.48601324]
 [0.50057757 0.10570783 0.50659805]]


In [3]:
# Indexing and slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])       # first element
print(arr[-1])      # last element
print(arr[1:4])     # slice
print(arr[::-1])    # reversed

10
50
[20 30 40]
[50 40 30 20 10]


In [4]:
# Reshaping and stacking
m = np.arange(12).reshape(3, 4)
print(m)

stacked_v = np.vstack([m, m])   # vertical stack
stacked_h = np.hstack([m, m])   # horizontal stack
print(stacked_v.shape, stacked_h.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(6, 4) (3, 8)


In [5]:
# Boolean masking
data = np.array([5, -2, 8, -1, 10, -6])
positive_only = data[data > 0]
print(positive_only)

[ 5  8 10]


In [6]:
# argmax, argsort, aggregation over axes
matrix = np.array([[1, 5, 3], [9, 2, 6]])
print(matrix.argmax())          # flattened index of max
print(matrix.argmax(axis=1))    # max index per row
print(matrix.argsort(axis=0))   # sorted indices per column
print(matrix.sum(axis=0))       # column-wise sum
print(matrix.mean(axis=1))      # row-wise mean

3
[1 0]
[[0 1 0]
 [1 0 1]]
[10  7  9]
[3.         5.66666667]


In [7]:
# Mean-centre a matrix (subtract column mean from each column)
def mean_centre(X):
    return X - X.mean(axis=0)

X = np.random.rand(5, 3)
print(mean_centre(X))

[[ 0.15560305 -0.27579102  0.14812619]
 [-0.38246141 -0.25142447  0.06669379]
 [ 0.20710675  0.25638124 -0.40619152]
 [-0.19610582  0.09659951  0.12582554]
 [ 0.21585744  0.17423474  0.065546  ]]


In [8]:
# Normalise rows to unit length
def normalise_rows(X):
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    return X / norms

print(normalise_rows(X))

[[0.67073706 0.11039636 0.73343333]
 [0.17873562 0.20046192 0.96325936]
 [0.73095312 0.66130708 0.1684651 ]
 [0.33890087 0.53488837 0.77397715]
 [0.64654949 0.50365479 0.57297958]]


In [9]:
# Pairwise Euclidean distances between two sets of points
def pairwise_distances(A, B):
    # A: (n, d), B: (m, d) -> output (n, m)
    diff = A[:, np.newaxis, :] - B[np.newaxis, :, :]
    return np.sqrt((diff ** 2).sum(axis=2))

A = np.random.rand(4, 2)
B = np.random.rand(3, 2)
print(pairwise_distances(A, B))

[[0.35735214 0.12703118 0.80738246]
 [0.72900335 0.55530487 0.65213386]
 [0.52133429 0.62525613 0.3415249 ]
 [0.34089383 0.55562294 0.64135519]]


In [10]:
# One-hot encode an integer label array
def one_hot(labels, num_classes):
    return np.eye(num_classes)[labels]

labels = np.array([0, 2, 1, 3])
print(one_hot(labels, 4))

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [11]:
def cosine_similarity(X):
    # X: (n, d) -> returns (n, n) similarity matrix
    norm_X = normalise_rows(X)
    return norm_X @ norm_X.T

np.random.seed(42)
data_100x20 = np.random.rand(100, 20)
sim_matrix = cosine_similarity(data_100x20)

# Find two most similar rows (excluding self-similarity on diagonal)
np.fill_diagonal(sim_matrix, -1)  # ignore self-matches
i, j = np.unravel_index(sim_matrix.argmax(), sim_matrix.shape)
print(f"Most similar rows: {i} and {j}, similarity = {sim_matrix[i, j]:.4f}")

Most similar rows: 13 and 88, similarity = 0.9342


In [12]:
import time

big_array = np.random.rand(1_000_000)

# Loop version
start = time.time()
result_loop = np.empty_like(big_array)
for k in range(len(big_array)):
    result_loop[k] = big_array[k] ** 2
loop_time = time.time() - start

# Vectorised version
start = time.time()
result_vec = big_array ** 2
vec_time = time.time() - start

print(f"Loop time: {loop_time:.4f}s")
print(f"Vectorised time: {vec_time:.6f}s")
print(f"Speedup: {loop_time / vec_time:.1f}x")

Loop time: 0.9147s
Vectorised time: 0.003453s
Speedup: 264.9x


In [13]:
A = np.random.rand(32, 128)
B = np.random.rand(128, 10)
b = np.random.rand(128)

# Predict shapes first (mentally), then verify:
product = A @ B
print("A @ B shape:", product.shape)   # expected (32, 10)

sum_result = A + b
print("A + b shape:", sum_result.shape)  # expected (32, 128), broadcasting

A @ B shape: (32, 10)
A + b shape: (32, 128)


## Shape Drill Predictions

Given A (32, 128) and B (128, 10):

- **A @ B**: My prediction is (32, 10) — because matrix 
  multiplication removes the inner matching dimension (128) 
  and keeps the outer dimensions.

- **A + b** where b is (128,): My prediction is (32, 128) — 
  because NumPy broadcasts the 1D array `b` across every row 
  of A, since b's shape matches A's last dimension.

Verified in code below — both predictions were correct.

In [14]:
def matmul_loops(A, B):
    n, m = A.shape
    m2, p = B.shape
    result = np.zeros((n, p))
    for i in range(n):
        for j in range(p):
            for k in range(m):
                result[i, j] += A[i, k] * B[k, j]
    return result

small_A = np.random.rand(20, 20)
small_B = np.random.rand(20, 20)

start = time.time()
r1 = matmul_loops(small_A, small_B)
t1 = time.time() - start

start = time.time()
r2 = small_A @ small_B
t2 = time.time() - start

start = time.time()
r3 = np.einsum('ik,kj->ij', small_A, small_B)
t3 = time.time() - start

print(f"Loops: {t1:.4f}s, @: {t2:.6f}s, einsum: {t3:.6f}s")

Loops: 0.0141s, @: 0.000282s, einsum: 0.000343s
